### ISSUE TITLE
PR456 / SiPixel / Filip / Online + offline: add phase0 check for certain plots

### ISSUE THREAD

**Issue by vanbesien** [cms-DQM/PR-workflow-tracking-for-DQM-GUI#50]

**Comment by vanbesien** [comment]
The changed code is horrible: Whitespace errors in basically every line he changed and horrible style.

**Comment by vanbesien** [comment]
After some updates the code come to something acceptable

**Comment by threus** [comment]
superseded by #52 , removed from the GUI
